name: Complex Workflow
env:
  WORKFLOW_NAME: "Complex workflow"
  ARTIFACT_NAME: test-artifact
  
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: TSQL Lint
        uses: lowlydba/tsqllint-action@v.1.3.2
        with: 
          path: "./*.sql"
          config: "./.github/linters/.tsqllintrc"

  secrets:
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - name: Echo the secret
        run: echo ${{ secrets.TEST_SECRET }}

  showvariables:
    runs-on: windows-latest
    needs: [secrets]
    steps:
      - name: Echo the variables
        run: $env:WORKFLOW_NAME

  upload_artifacts:
    runs-on: ubuntu-latest
    needs: [showvariables]
    steps:
      - name: Build artifact
        run: go build ${{ env.ARTIFACT_NAME }}.go
        
      - name: Upload artifact
        uses: actions/upload-artifact@3.0
        with: 
          name: Test_artifact
          path: ./${{env.ARTIFACT_NAME}}
        
  uBuntu:
    runs-on: ubuntu-latest
    steps:
    - name: Get the latest date
      run: date

  windows:
    runs-on: windows-latest
    steps:
    - name: Get the latest date
      run: date

  depends:
    runs-on: ubuntu-latest
    needs: [uBuntu, windows]
    steps:
    - name: Get the latest date
      run: date
      
