name: Complex Workflow
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: TSQL Lint
        uses: lowlydba/tsqllint-action@v1.0.0
        with: 
          path: "*.sql *.SQL"
          config: "./.github/linters/.tsqllintrc"

  uBuntu:
    runs-on: ubuntu-latest
    steps:
    - name: Get the latest date
      run: date

  windows:
    runs-on: windows-latest
    steps:
    - name: Get the latest date
      run: date

  macos:
    runs-on: macos-latest
    steps:
    - name: Get the latest date
      run: date

  depends:
    runs-on: ubuntu-latest
    needs: [uBuntu, windows, macos]
    steps:
    - name: Get the latest date
      run: date
      
