name: Complex Workflow
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: TSQL Lint
        uses: lowlydba/tsqllint-action@v.1.3.2
        with: 
          path: "./*.sql"
          config: "./.github/linters/.tsqllintrc"

  secrets:
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - name: Echo the secret
        run: echo ${{ secrets.TEST_SECRET }}
      
  uBuntu:
    runs-on: ubuntu-latest
    steps:
    - name: Get the latest date
      run: date

  windows:
    runs-on: windows-latest
    steps:
    - name: Get the latest date
      run: date

  depends:
    runs-on: ubuntu-latest
    needs: [uBuntu, windows]
    steps:
    - name: Get the latest date
      run: date
      
